name = "gdh-website"
pages_build_output_dir = "."
compatibility_date = "2026-04-12"

[[d1_databases]]
binding = "DB"
database_name = "gdh-locations"
database_id = "2be0a353-03d9-40d0-8b22-406e437f3baf"
